# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            '在Windows上运行Jekyll'
url:              https://blog.kafuziroh.cc/run-jekyll-on-windows
baseurl:          /run-jekyll-on-windows

github:
  repo:           https://github.com/Kafuziroh/run-jekyll-on-windows/tree/gh-pages_zh-CN

author:
  name:           '雨空CA@かふう(Kafuziroh)'
  url:            https://twitter.com/Kafuziroh
